import { Question } from './types';

export const QUESTIONS: Question[] = [
  { id: 1, category: 0, text: '¿Qué tres niveles forman la diversidad de la naturaleza?', options: ['Clima, agua y suelo', 'Genes, especies y ecosistemas', 'Plantas, animales y hongos', 'Local, regional y global'], correctIndex: 1, explanation: 'La variedad natural se analiza en tres niveles conectados: diversidad genética dentro de las especies, diversidad de especies y diversidad de ecosistemas.' },
  { id: 2, category: 0, text: 'Una especie endémica es aquella que…', options: ['Solo vive de noche', 'Se encuentra de forma natural en una zona limitada', 'Ha sido introducida por personas', 'Es abundante en todo el mundo'], correctIndex: 1, explanation: 'Las especies endémicas tienen una distribución natural restringida. Esa limitación puede aumentar su vulnerabilidad ante cambios locales.' },
  { id: 3, category: 0, text: '¿Por qué la diversidad genética mejora la resiliencia de una población?', options: ['Elimina toda competencia', 'Aumenta la probabilidad de que algunos individuos toleren cambios', 'Impide las enfermedades', 'Hace que todas las especies sean iguales'], correctIndex: 1, explanation: 'Una población genéticamente diversa dispone de más respuestas posibles ante enfermedades, variaciones climáticas u otras presiones.' },
  { id: 4, category: 0, text: '¿Qué función ecológica realizan muchos insectos, aves y murciélagos?', options: ['Compactar el suelo', 'Polinizar plantas', 'Aumentar la contaminación lumínica', 'Crear especies invasoras'], correctIndex: 1, explanation: 'La polinización permite la reproducción de numerosas plantas silvestres y cultivos, y sostiene redes alimentarias completas.' },
  { id: 5, category: 0, text: '¿Qué diferencia principal hay entre una especie exótica y una invasora?', options: ['Ninguna', 'La invasora causa impactos al establecerse y propagarse', 'La exótica siempre es venenosa', 'La invasora solo vive en ciudades'], correctIndex: 1, explanation: 'No toda especie introducida es invasora. Se considera invasora cuando su expansión genera daños ecológicos, económicos o sociales.' },
  { id: 6, category: 0, text: 'Antes de una obra en época de cría, ¿qué medida aporta mejor información?', options: ['Empezar y observar después', 'Realizar una prospección ecológica previa', 'Aumentar la iluminación', 'Retirar toda la vegetación'], correctIndex: 1, explanation: 'Una prospección previa permite detectar nidos, refugios o especies sensibles y adaptar calendario, diseño y medidas preventivas.' },
  { id: 7, category: 0, text: '¿Por qué la iluminación nocturna puede afectar a la fauna?', options: ['Porque mejora todos los hábitats', 'Porque altera orientación, actividad y ciclos biológicos', 'Porque reduce el ruido', 'Porque aumenta la diversidad genética'], correctIndex: 1, explanation: 'La luz artificial nocturna puede modificar rutas, alimentación, reproducción y relaciones depredador-presa. Debe justificarse, orientarse y limitarse.' },
  { id: 8, category: 0, text: 'Si desaparece una especie clave de una red trófica, ¿qué puede ocurrir?', options: ['Nada, todas son intercambiables', 'Efectos en cascada sobre otras poblaciones', 'Solo cambia el paisaje visual', 'Aumenta automáticamente la estabilidad'], correctIndex: 1, explanation: 'Las relaciones ecológicas conectan a las especies. La pérdida de una especie clave puede alterar abundancias, hábitats y funciones del ecosistema.' },

  { id: 101, category: 1, text: '¿Qué son los servicios ecosistémicos?', options: ['Servicios de jardinería', 'Contribuciones de los ecosistemas al bienestar y la actividad humana', 'Solo productos agrícolas', 'Únicamente espacios protegidos'], correctIndex: 1, explanation: 'Incluyen provisión, regulación, valores culturales y procesos ecológicos de soporte. Las organizaciones dependen de ellos directa e indirectamente.' },
  { id: 102, category: 1, text: '¿Qué servicio puede prestar un humedal bien conservado?', options: ['Aumentar la erosión', 'Regular inundaciones y depurar agua', 'Eliminar todas las especies', 'Evitar cualquier sequía'], correctIndex: 1, explanation: 'Los humedales almacenan agua, retienen sedimentos y nutrientes y ofrecen hábitat. No eliminan todo riesgo, pero pueden reducirlo.' },
  { id: 103, category: 1, text: '¿Qué significa conectividad ecológica?', options: ['Tener wifi en el campo', 'Permitir el movimiento de organismos entre hábitats', 'Unir edificios con carreteras', 'Concentrar la fauna en un recinto'], correctIndex: 1, explanation: 'La conectividad facilita dispersión, migración e intercambio genético. Los corredores y pasos de fauna reducen el aislamiento.' },
  { id: 104, category: 1, text: 'Un suelo sano debe entenderse como…', options: ['Un soporte inerte', 'Un sistema vivo que regula agua, nutrientes y carbono', 'Un residuo de construcción', 'Una superficie que siempre debe sellarse'], correctIndex: 1, explanation: 'El suelo alberga organismos, almacena carbono, filtra agua y sostiene vegetación. Su sellado o contaminación reduce esas funciones.' },
  { id: 105, category: 1, text: '¿Cuál es un efecto habitual de fragmentar un hábitat?', options: ['Mejorar todos los desplazamientos', 'Aislar poblaciones y aumentar los efectos de borde', 'Eliminar la necesidad de seguimiento', 'Crear más diversidad automáticamente'], correctIndex: 1, explanation: 'La fragmentación divide áreas continuas en parches, dificulta movimientos y expone más superficie a ruido, luz, depredación u otras presiones.' },
  { id: 106, category: 1, text: '¿Para qué sirve una línea base ecológica?', options: ['Para justificar una decisión ya tomada', 'Para conocer el estado inicial y comparar cambios', 'Para sustituir el seguimiento', 'Para medir solo emisiones'], correctIndex: 1, explanation: 'La línea base describe el estado previo con métodos y límites claros. Sin ella es difícil atribuir mejoras o deterioros a una actuación.' },
  { id: 107, category: 1, text: '¿Qué caracteriza a una solución basada en la naturaleza?', options: ['Imitar el color verde', 'Abordar un reto social protegiendo o restaurando ecosistemas', 'Plantar árboles en cualquier lugar', 'Sustituir toda infraestructura'], correctIndex: 1, explanation: 'Una solución basada en la naturaleza debe responder a un reto y aportar beneficios ecológicos verificables, con diseño adecuado al contexto local.' },
  { id: 108, category: 1, text: '¿Por qué importa la escala de paisaje?', options: ['Porque un recinto nunca se conecta con su entorno', 'Porque agua, especies y presiones atraviesan los límites de una instalación', 'Porque solo cuentan los mapas nacionales', 'Porque evita consultar a actores locales'], correctIndex: 1, explanation: 'Los procesos ecológicos no siguen las lindes administrativas. Evaluar cuenca, corredores y usos vecinos mejora la calidad de las decisiones.' },

  { id: 201, category: 2, text: '¿Cuál es la diferencia entre impacto y dependencia de la naturaleza?', options: ['Son sinónimos', 'Impacto es el cambio causado; dependencia es lo que la actividad necesita', 'La dependencia siempre es positiva', 'El impacto solo ocurre fuera de la empresa'], correctIndex: 1, explanation: 'Una actividad puede afectar a la naturaleza y, al mismo tiempo, depender de agua, regulación climática, materiales o estabilidad del suelo.' },
  { id: 202, category: 2, text: '¿Qué enfoque identifica impactos desde materias primas hasta el fin de vida?', options: ['Pensamiento de ciclo de vida', 'Inspección visual única', 'Marketing ambiental', 'Contabilidad financiera aislada'], correctIndex: 0, explanation: 'El ciclo de vida evita trasladar impactos entre etapas o lugares y permite comparar alternativas con límites consistentes.' },
  { id: 203, category: 2, text: '¿Qué presión suele generar el sellado de suelo?', options: ['Pérdida de infiltración y hábitat', 'Mayor conectividad ecológica', 'Recuperación automática del suelo', 'Menos escorrentía en todos los casos'], correctIndex: 0, explanation: 'Las superficies impermeables reducen infiltración, alteran drenaje y eliminan funciones del suelo. Evitar y minimizar superficie ocupada es prioritario.' },
  { id: 204, category: 2, text: 'Para evaluar riesgo hídrico de una instalación, ¿qué combinación es más útil?', options: ['Solo consumo anual', 'Consumo, estado de la cuenca y necesidades de otros usuarios', 'Solo precio del agua', 'Número de grifos'], correctIndex: 1, explanation: 'Un mismo consumo tiene implicaciones distintas según disponibilidad, calidad, estacionalidad y competencia por el recurso en la cuenca.' },
  { id: 205, category: 2, text: '¿Qué mejora la trazabilidad ambiental de una compra?', options: ['Conocer origen, material, proveedor y evidencias', 'Usar una etiqueta verde sin criterios', 'Elegir siempre la opción más barata', 'Evitar preguntas al proveedor'], correctIndex: 0, explanation: 'La trazabilidad permite localizar riesgos en la cadena de valor y verificar requisitos, certificaciones y planes de mejora.' },
  { id: 206, category: 2, text: '¿Cuál es un riesgo físico relacionado con la naturaleza?', options: ['Escasez de agua que interrumpe operaciones', 'Cambio de logotipo', 'Una campaña interna', 'Un premio de comunicación'], correctIndex: 0, explanation: 'La degradación de ecosistemas puede agravar sequías, inundaciones, erosión o pérdida de materias primas y afectar la continuidad operativa.' },
  { id: 207, category: 2, text: 'Una sustancia derramada puede afectar a un ecosistema principalmente por…', options: ['Su ruta de exposición, concentración y persistencia', 'El color del envase', 'La edad del edificio', 'El número de reuniones'], correctIndex: 0, explanation: 'La evaluación debe seguir la vía desde la fuente al receptor: drenajes, suelo, aguas superficiales o subterráneas y organismos expuestos.' },
  { id: 208, category: 2, text: '¿Qué riesgo existe al mirar solo el recinto propio?', options: ['Ninguno', 'Ignorar impactos relevantes de proveedores, logística y uso de materiales', 'Medir demasiado', 'Reducir costes siempre'], correctIndex: 1, explanation: 'Una parte importante de la huella puede estar en la cadena de valor. Hay que priorizarla según materialidad, influencia y calidad de datos.' },

  { id: 301, category: 3, text: '¿Cuál es el orden correcto de la jerarquía de mitigación?', options: ['Compensar, restaurar, minimizar, evitar', 'Evitar, minimizar, restaurar y, por último, compensar', 'Restaurar, evitar, compensar, minimizar', 'Medir, comunicar, compensar, cerrar'], correctIndex: 1, explanation: 'Primero se evita el impacto; después se minimiza lo inevitable, se restaura lo afectado y solo los impactos residuales se consideran para compensación.' },
  { id: 302, category: 3, text: '¿Por qué compensar no sustituye a evitar?', options: ['Porque siempre cuesta menos', 'Porque algunos valores naturales son irremplazables o tardan décadas en recuperarse', 'Porque no requiere seguimiento', 'Porque elimina la necesidad de diseño'], correctIndex: 1, explanation: 'La compensación tiene incertidumbre, retrasos y límites ecológicos. No legitima destruir un valor crítico que podía conservarse.' },
  { id: 303, category: 3, text: '¿Qué medida aplica mejor el principio de evitar?', options: ['Reubicar una obra fuera de un hábitat sensible', 'Plantar después de construir', 'Pagar una campaña', 'Medir el daño al final'], correctIndex: 0, explanation: 'Cambiar ubicación, diseño o calendario antes de generar el impacto suele ser más eficaz y seguro que reparar posteriormente.' },
  { id: 304, category: 3, text: '¿Qué necesita un plan de restauración sólido?', options: ['Solo una lista de plantas', 'Objetivo, referencia ecológica, acciones, indicadores y mantenimiento', 'Una foto del primer día', 'Una promesa sin plazo'], correctIndex: 1, explanation: 'Restaurar es recuperar estructura, funciones y trayectoria ecológica. Requiere objetivos medibles y gestión durante el tiempo necesario.' },
  { id: 305, category: 3, text: 'Para reducir impacto de luz nocturna, la primera pregunta debería ser…', options: ['¿Podemos instalar más focos?', '¿Es necesaria, dónde y durante cuánto tiempo?', '¿Qué color queda mejor?', '¿Puede verse desde lejos?'], correctIndex: 1, explanation: 'La secuencia es evitar iluminación innecesaria y después limitar intensidad, horario, orientación y espectro según receptores sensibles.' },
  { id: 306, category: 3, text: '¿Qué es gestión adaptativa?', options: ['Mantener el plan aunque falle', 'Ajustar las medidas con resultados de seguimiento', 'Cambiar objetivos cada semana', 'Actuar sin indicadores'], correctIndex: 1, explanation: 'Se definen umbrales y respuestas antes de actuar. Los datos de seguimiento permiten corregir medidas cuando no alcanzan el resultado previsto.' },
  { id: 307, category: 3, text: '¿Qué criterio evita introducir plantas inadecuadas en una restauración?', options: ['Usar especies nativas compatibles con el lugar', 'Elegir solo por crecimiento rápido', 'Comprar la mezcla más barata', 'Usar cualquier especie ornamental'], correctIndex: 0, explanation: 'La procedencia, diversidad y adecuación al suelo y clima importan. También debe controlarse el riesgo de invasoras y la disponibilidad de mantenimiento.' },
  { id: 308, category: 3, text: '¿Qué significa adicionalidad en una medida de compensación?', options: ['Que el resultado habría ocurrido igualmente', 'Que genera una mejora que no se produciría sin la intervención', 'Que no necesita pruebas', 'Que solo añade presupuesto'], correctIndex: 1, explanation: 'Una medida adicional aporta un resultado por encima de obligaciones y tendencias existentes; debe demostrarse con una referencia creíble.' },

  { id: 401, category: 4, text: '¿Cuál es un indicador de estado?', options: ['Hectáreas ocupadas', 'Calidad ecológica de un humedal', 'Número de reuniones', 'Presupuesto asignado'], correctIndex: 1, explanation: 'Los indicadores de estado describen la condición de la naturaleza. Las hectáreas ocupadas son una presión y las acciones realizadas son respuestas.' },
  { id: 402, category: 4, text: '¿Qué hace que un indicador sea útil para decidir?', options: ['Que sea fácil de publicar', 'Que sea relevante, medible, comparable y vinculado a un objetivo', 'Que siempre aumente', 'Que no tenga unidad'], correctIndex: 1, explanation: 'Un buen indicador tiene definición, método, frecuencia, responsable, línea base y umbral o meta que active decisiones.' },
  { id: 403, category: 4, text: '¿Por qué contar árboles plantados no demuestra por sí solo una mejora?', options: ['Porque los árboles no importan', 'Porque mide actividad, no supervivencia, adecuación ni función ecológica', 'Porque siempre son demasiados', 'Porque no se pueden contar'], correctIndex: 1, explanation: 'La actividad debe conectarse con resultados: supervivencia, diversidad, estructura, conectividad y funciones recuperadas a lo largo del tiempo.' },
  { id: 404, category: 4, text: '¿Qué debe acompañar a una afirmación ambiental?', options: ['Un color verde', 'Alcance, periodo, método, datos y limitaciones', 'Solo una fotografía', 'Una frase absoluta'], correctIndex: 1, explanation: 'La comunicación responsable permite verificar la afirmación y evita ocultar incertidumbres, impactos residuales o límites del análisis.' },
  { id: 405, category: 4, text: '¿Para qué sirve un indicador de presión?', options: ['Para medir la causa o intensidad de un impacto', 'Para describir únicamente reputación', 'Para reemplazar la línea base', 'Para contar premios'], correctIndex: 0, explanation: 'Superficie ocupada, ruido, vertido o consumo de agua son presiones. Deben relacionarse con el estado de los receptores ecológicos.' },
  { id: 406, category: 4, text: 'Si los datos son incompletos, ¿qué práctica es correcta?', options: ['Ocultarlo', 'Documentar incertidumbre, usar supuestos prudentes y mejorar el dato', 'Inventar una cifra', 'Cancelar todo seguimiento'], correctIndex: 1, explanation: 'La incertidumbre no impide decidir, pero debe ser visible. Los supuestos conservadores y un plan de mejora reducen el riesgo de falsa precisión.' },
  { id: 407, category: 4, text: '¿Qué aporta combinar datos de teledetección y trabajo de campo?', options: ['Escala espacial y validación local', 'Eliminar toda incertidumbre', 'Evitar visitas siempre', 'Medir solo costes'], correctIndex: 0, explanation: 'La observación remota cubre grandes áreas y series temporales; el campo confirma especies, condición y causas que una imagen no siempre distingue.' },
  { id: 408, category: 4, text: '¿Qué pregunta ayuda a priorizar un asunto de naturaleza?', options: ['¿Es el gráfico atractivo?', '¿Qué magnitud, sensibilidad, dependencia e influencia tenemos?', '¿Cuántos colores usa?', '¿Puede resumirse en una palabra?'], correctIndex: 1, explanation: 'La priorización combina importancia del impacto o dependencia, sensibilidad del lugar, riesgo para la organización y capacidad de influir.' },

  { id: 501, category: 5, text: 'En una zona de mantenimiento del A400M aparece una mancha cerca de un drenaje. ¿Qué se hace primero?', options: ['Lavarla hacia el drenaje', 'Detener la fuente, contener y activar el protocolo de incidente', 'Esperar a que se evapore', 'Cubrirla con tierra'], correctIndex: 1, explanation: 'La prioridad es proteger personas y medio, cortar la fuente y evitar que el contaminante alcance suelo o agua. Después se notifica, recupera y analiza la causa.' },
  { id: 502, category: 5, text: 'Una prueba asociada al Eurofighter coincide con una zona y periodo sensibles para aves. ¿Qué respuesta aplica mejor la jerarquía?', options: ['Mantenerla sin cambios', 'Revisar ruta, horario o fecha para evitar la afección', 'Compensar antes de evaluar', 'Aumentar el número de vuelos'], correctIndex: 1, explanation: 'La planificación operacional puede evitar la coincidencia espacial o temporal. Si queda impacto, se evalúan medidas adicionales y restricciones de seguridad.' },
  { id: 503, category: 5, text: 'Para ampliar una instalación, ¿qué alternativa debe analizarse primero?', options: ['La que ocupa el hábitat más sensible', 'Reutilizar suelo ya transformado y reducir nueva ocupación', 'La más visible desde la carretera', 'La que exige más iluminación'], correctIndex: 1, explanation: 'La reutilización de áreas ya alteradas puede evitar nueva pérdida de suelo y hábitat, siempre que se comprueben contaminación, seguridad y viabilidad.' },
  { id: 504, category: 5, text: '¿Cómo puede compatibilizarse la gestión de fauna con la seguridad aeronáutica?', options: ['Atrayendo fauna a pistas', 'Diseñando el hábitat y las medidas con evaluación conjunta de riesgos', 'Ignorando los movimientos de aves', 'Eliminando toda vegetación sin análisis'], correctIndex: 1, explanation: 'La seguridad es prioritaria, pero las medidas deben basarse en especies, comportamiento y contexto para no crear nuevos atractores ni impactos innecesarios.' },
  { id: 505, category: 5, text: 'En una compra de embalajes de madera, ¿qué evidencia es más útil?', options: ['Que el embalaje sea verde', 'Origen trazable y gestión forestal verificada', 'Una promesa verbal', 'El menor peso sin más datos'], correctIndex: 1, explanation: 'La trazabilidad y la verificación permiten reducir riesgos de deforestación o aprovechamiento ilegal en la cadena de suministro.' },
  { id: 506, category: 5, text: '¿Qué mejora un plan de siega en terrenos industriales?', options: ['Segar todo el año con la misma frecuencia', 'Ajustar zonas y calendario a seguridad, incendios y ciclos ecológicos', 'Eliminar el seguimiento', 'Introducir especies invasoras'], correctIndex: 1, explanation: 'Una gestión diferenciada puede mantener visibilidad y seguridad, reducir recursos y favorecer hábitat, evitando periodos críticos cuando sea posible.' },
  { id: 507, category: 5, text: '¿Qué valor aporta la observación de la Tierra a la gestión ambiental?', options: ['Sustituye siempre el trabajo de campo', 'Ayuda a detectar cambios y priorizar verificaciones', 'Elimina la necesidad de contexto', 'Solo produce imágenes decorativas'], correctIndex: 1, explanation: 'Las series satelitales permiten observar cobertura, humedad o cambios del territorio. Su interpretación debe validarse con conocimiento local y datos de campo.' },
  { id: 508, category: 5, text: 'Tras implantar una medida ambiental en una planta, ¿qué cierra el ciclo de gestión?', options: ['Publicar una foto', 'Medir resultados, comparar con umbrales y corregir si es necesario', 'Dar la acción por terminada', 'Cambiar el nombre del proyecto'], correctIndex: 1, explanation: 'La eficacia no se presume: se comprueba. El seguimiento convierte una acción aislada en aprendizaje y mejora continua.' },
];

export function getRandomQuestion(category: number, usedIds: number[]): Question | null {
  const categoryQuestions = QUESTIONS.filter((question) => question.category === category);
  const available = categoryQuestions.filter((question) => !usedIds.includes(question.id));
  const pool = available.length > 0 ? available : categoryQuestions;
  return pool[Math.floor(Math.random() * pool.length)] ?? null;
}
